"""empty message

Revision ID: 9349f817c924
Revises: a9472473db45
Create Date: 2023-06-28 08:05:50.059187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9349f817c924'
down_revision = 'a9472473db45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offre_emploi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruteur_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recruteur', ['recruteur_id'], ['id_recruteur'])
        batch_op.drop_column('idc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offre_emploi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idc', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recruteur', ['idc'], ['id_recruteur'])
        batch_op.drop_column('recruteur_id')

    # ### end Alembic commands ###
